#!/usr/bin/env bash
# Default ports for vk-* scripts (override via env before vk-start).

: "${VK_FRONTEND_PORT:=13001}"
: "${VK_BACKEND_PORT:=13002}"
: "${VK_PREVIEW_PROXY_PORT:=13003}"
: "${VK_REMOTE_PORT:=13000}"
: "${VK_RELAY_PORT:=18082}"
: "${VK_REMOTE_DB_PORT:=15433}"
: "${VK_MOBILE_HTTPS_PORT:=13001}"
: "${VK_MOBILE_RELAY_HTTPS_PORT:=18443}"
: "${VK_BIND_ADDR:=0.0.0.0}"

export VK_FRONTEND_PORT VK_BACKEND_PORT VK_PREVIEW_PROXY_PORT
export VK_REMOTE_PORT VK_RELAY_PORT VK_REMOTE_DB_PORT
export VK_MOBILE_HTTPS_PORT VK_MOBILE_RELAY_HTTPS_PORT
export VK_BIND_ADDR
